pause Insert Master Key Version 3.0 Disk # 1
dir g:
erase g:*.*
copy c:mkmenu.asm g:
copy c:mkdata.asm g:
copy c:mklook.asm g:
copy c:mkdisu.asm g:
copy c:mkerru.asm g:
copy c:mkpmptu.asm g:
copy c:mkint13.asm g:
pause Insert Master Key Version 3.0 Disk # 2
dir g:
erase g:*.*
copy c:mkcopyu.asm g:
copy c:mkmapu.asm g:
copy c:mkkeyu.asm g:
copy c:mk*.inc
copy c:hello g:
copy mk*.bat g:
copy mk*.lnk g:
copy mk.com g:. ik#2
i :
rs :.cp :koy.s :
oycmmp.s :
oycmky.s :
oycm*ic
oychlogcp k.a