erase c:*.bak
erase c:*.obj
basic printer
asm c:mkmenu.asm,c:mkmenu.obj,lpt1:;
basic printer
asm c:mkcopyu.asm,c:mkcopyu.obj,lpt1:;
basic printer
asm c:mkmapu.asm,c:mkmapu.obj,lpt1:;
basic printer
asm c:mklook.asm,c:mklook.obj,lpt1:;
basic printer
asm c:mkpmptu.asm,c:mkpmptu.obj,lpt1:;
basic printer
asm c:mkdisu.asm,c:mkdisu.obj,lpt1:;
basic printer
asm c:mkkeyu.asm,c:mkkeyu.obj,lpt1:;
basic printer
asm c:mkerru.asm,c:mkerru.obj,lpt1:;
basic printer
asm c:mkint13.asm,c:mkint13.obj,lpt1:;
basic printer
asm c:mkdata.asm,c:mkdata.obj,lpt1:;
basic printer
mklnk


ai rneamcmdt.s,:kaaojlt:bscpitr
kna nmmts:aol:bcirk msalbikslisissneamcmer.s,:kruojlt:bscpitr
s :kn1.s,:kn1.b,p1;ë Š¢0 0ÈFé   (
H € ˆŠ
ˆÃÓ0ÏrÃÓKèÓÀ•µş¢3ş