erase c:*.bak
erase c:*.obj
asm c:mkmenu.asm,c:mkmenu.obj;
asm c:mkcopyu.asm,c:mkcopyu.obj;
asm c:mkmapu.asm,c:mkmapu.obj;
asm c:mklook.asm,c:mklook.obj;
asm c:mkpmptu.asm,c:mkpmptu.obj;
asm c:mkdisu.asm,c:mkdisu.obj;
asm c:mkkeyu.asm,c:mkkeyu.obj;
asm c:mkerru.asm,c:mkerru.obj;
asm c:mkint13.asm,c:mkint13.obj;
asm c:mkdata.asm,c:mkdata.obj;
mklnknlamcmer.s,:kruojamcmit3amcmit3ojamcmdt.s,:kaaojmlklmmrs:rommtaci3jacd.,kajmkmsrmaijc.kjkmrmickkrikrkkiuojamcmky.s,:keuoj:kaaojlt:mlktmmys: